### PR TITLE
Update README for correctness

### LINKED ISSUE #97: When setting up a new environment, `mix test` errors on "Wallaby can't find phantomjs"
README needs to be updated to include the need for phantomjs to be installed.

Error message:

```
** (MatchError) no match of right hand side value: {:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Wallaby.DependencyException{message: "Wallaby can't find phantomjs. Make sure you have phantomjs installed\nand included in your path, or that your `config :wallaby, :phantomjs`\nsetting points to a valid phantomjs executable.\n"}, [{Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 29]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 273]}]}}}}}}
    test/test_helper.exs:9: (file)
    (elixir) lib/code.ex:677: Code.require_file/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (mix) lib/mix/tasks/test.ex:256: Mix.Tasks.Test.run/1
```

Resolved by `brew install phantomjs` on macOS High Sierra.

### PR DESCRIPTION
**Pull request by tmecklem**
Fixes #97 and #101 

These changes address missing parts of the README that were encountered while setting up a new development environment.

### CODE REVIEW

**Comment by KronicDeth** [comment]
The ci/circleci: sobelow should not have passed.  It has a 0-exit-code error:

```
mix sobelow --config
Checking Sobelow version...

Error fetching version number.


19:55:39.907 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'cipher', 32, 'received SERVER ALERT: Fatal - Bad Record MAC', 10]
This does not appear to be a Phoenix application.
````

**Comment by alexgaribay** [comment]
Here's where the issue is: https://github.com/poanetwork/poa-explorer/blob/cc84cce202f82e677be4eef5806276a610da1d99/.circleci/config.yml#L284-L299. I think it needs to be updated to point to the `explorer_web` app. The root be specified with the `--root` options.

```
 mix sobelow --root apps/explorer_web
```

**Comment by tmecklem** [comment]
Output of sobelow on CircleCI is now:

```
WARNING: Sobelow cannot find the router. If this is a Phoenix application
please use the `--router` flag to specify the router's location.

WARNING: Could not read web directory.
```

but locally the output from sobelow version 0.6.6 is

```
WARNING: Web directory was not found in the expected location.
This may be a result of non-standard directory structure, or use
of an umbrella project. All files in the "lib" directory were
scanned for vulnerabilities.
```

These warnings appear to be benign according to https://github.com/nccgroup/sobelow/issues/5#issuecomment-305791042

**Comment by tmecklem** [comment]
We changed it to run in each umbrella app in CircleCI and in the README. This seems to be the best option until https://github.com/nccgroup/sobelow/issues/31 is addressed.

@KronicDeth this is ready for another look when you have time.

**Pull request merged**
