### PR TITLE
[WIP] - Index token transfers

### LINKED ISSUE #48: Events Worker
Events hold the information for Token Transfers. Querying an event against this abi will provide to, from, value, and contract

```
[
  {
    "constant": true,
    "inputs": [],
    "name": "name",
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [],
    "name": "totalSupply",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [
      {
        "name": "_owner",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "name": "balance",
        "type": "uint256"
      }
    ],
    "payable": false,
    "type": "function"
  },
  {
    "constant": true,
    "inputs": [],
    "name": "symbol",
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "payable": false,
    "type": "function"
  }
]
```

Here is my code for obtaining events. I'm using past events but there is support for current block events:

```var contractAddress = req.query.contract
  var block = req.query.block

  var transferContract = new web3.eth.Contract(contractABI, contractAddress)

  transferContract.getPastEvents('Transfer', {
    filter: {},
    fromBlock: block,
    toBlock: block
  }, function (error, event) {
    if (error) {
      res.send('Error')
    } else {
      res.send(event)
    }
  })
})
```

### PR DESCRIPTION
**Pull request by alexgaribay**
Resolves #48.

## Overview

Token transfers are special cases within a log record. In the logs, a token transfer is signified by having `0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef` as the `first_topic` value. The `second_topic` and `third_topic` values are the from-address and the to-address of the transfer respectively. The `data` field in the log represents the amount of tokens that was transferred between addresses. Within the parent transaction of the log, the `to_address_hash` represents the smart contract address of the token that is being transferred. Within that contract contains functions that we must call to fetch information about the token and store.

## Remaining Work

Some work still remains for the PR to be feature-complete. Work in #279 is needed to execute smart contract functions of the token contract to get information about the token. Once that code is available, that code needs to be hooked up to `Explorer.Indexer.TokenTransfers`. There is a `TODO` marked where that code is along with the information that needs to be fetched about the token. There are also a few tests that need to be added to that module for 100% coverage.

- [ ] Fetch and store information about a token from executing the token's smart contract functions
- [ ] Add additional coverage for `Explorer.Indexer.TokenTransfers`

## Motivation

This PR adds indexing of token transfers which are signified by a special value in the logs.

### Enhancements
* Add indexing of logs that are token transfers and catalog them in their own table
* Add subscription mechanism for events related to new chain data being inserted

## Upgrading

Only a data migration is required for this PR.

### CODE REVIEW

**Comment by KronicDeth** [comment]
Rebased to be compatible after #304 merge

**Comment by Lucasnar** [comment]
I changed the base branch (and rebased) to `ln-read-smart-contract-back-end` because `Explorer.SmartContract.Reader` is going to be used here. Once that branch is fully merged, we go back to `master`.

**Comment by igorffs** [comment]
Hey @alexgaribay, can you tell me if these changes already consider Token's info updates? I'm not sure but, maybe only their total suply may change.

**Comment by alexgaribay** [comment]
@igorffs This branch does not consider token updates at the moment yet.

**Comment by igorffs** [comment]
@alexgaribay I have a suggestion that may help us deal with the blocks we're in. \o

The reason this PR is blocked is that we can't interact with Contracts yet, which is necessary so we can create unexistent Tokens in our database. Although, TokenTransfers are there and don't need all their tokens info to be indexed. 

IMO, this kind of data looks just like other info (Transaction, Logs, Blocks, Addresses and etc.) we're fetching from the network. So what do you think of indexing them the same way/time we do with the rest of our entities?

What prevents us from doing is the creation of a "full Token", but if we have its identification data (such as from address and contract_address_hash) we'd be able to create a temporary incomplete token that could be updated in a different process. I'm not sure about the updates on a token data yet, but this process could also serve this purpose.

I thought about a few trade-offs in this suggestion:

**Pros**
- We'd guarantee that TokenTransfers would be stored in the database along with the Blocks and Transactions.
- This would allow us to move forward in the Tokens epic even with the contract interaction block.
- We wouldn't need to use a queue/process state to control TokenTransfers indexing.

**Cons**
- The `BlockFetcher` would be responsible for extracting and storing two new entities (based on logs data).
- The token may appear without its data in the front-end for a while (depending on the process).

wdyt?

**Comment by acravenho** [comment]
@igorffs @alexgaribay I like your suggestions Igor but I could be wrong in that entering the `to`, `from`, `contract`, and `tokens transferred` is still blocked by the `ex_abi` repo. These values are formed like: `0x0000000000000000000000009a4a90e2732f3fa4087b0bb4bf85c76d14833df1` and need to be decoded by the `ex_abi` library to `0x9a4A90E2732F3Fa4087B0Bb4bF85c76d14833dF1`.

It would be great to get the db schema setup so we can have other teams work on to the frontend for tokens that are currently being blocked.

**Comment by alexgaribay** [comment]
@igorffs I supposed it can be indexed with the main indexer. So are you proposing delaying the fetching of Token information until the Read Contract feature is complete?

@acravenho I can still interpret addresses without the ABI library being updated.

**Comment by igorffs** [comment]
@alexgaribay it's something like that. It's more like an approach for indexing the data and then improving the data, I believe its similar of what we do with the BalanceFetcher or InternalTransactionFetcher.

I think this can help both with the dependency we have on this PR, but also it does also change how we're handling the indexing of this kind of data. If we look at it as dependency removal only, we can just move the migrations to a new PR and merge it in master (which is what @acravenho has suggested).

Although I'm not completely sure about it and I think it'd be great to hear your thoughts on it. We could have a call to talk about, wdyt?

**Comment by alexgaribay** [comment]
@igorffs I'm actually running in to cases where the recipient's address isn't already index and I'm getting association errors. Since this is the case, I'm going go ahead and move it all into the main indexer. The token information will have to be retrieved asynchronously outside of the main indexer.

**Comment by igorffs** [comment]
Nice @alexgaribay! ❤️ Let me know if I can help you with anything. 🙌

**Comment by alexgaribay** [comment]
Closed due to change in indexer design. See #484 for successor PR.

**Pull request closed without merging**
