### PR TITLE
Dynamically add websocket endpoint to CSP

### LINKED ISSUE #414: Deploy- Refused to connect violates Content Security Policy
I receive the following error on the deployed version of explorer:

```
Refused to connect to 'ws://sokll-explorer-sokol-elb-852408732.us-east-1.elb.amazonaws.com/socket/websocket?locale=en&vsn=2.0.0' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:*
```

### Environment

* Operating System: Linux

### Steps to reproduce

Deploy explorer via `https://github.com/poanetwork/poa-explorer-infra`

### PR DESCRIPTION
**Pull request by jimmay5469**
Resolves #414

### Bug Fixes
- Fix CSP to allow connection to the explorer_web websocket endpoint in order to support live updates.

### CODE REVIEW

**Comment by acravenho** [comment]
I'm receiving the following error on deployment:

```
Refused to connect to 'ws://sokll-explorer-sokol-elb-852408732.us-east-1.elb.amazonaws.com/socket/websocket?locale=en&vsn=2.0.0' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:4000 wss://localhost:4000".
```

**Comment by jimmay5469** [comment]
Strange, I'll do some more digging then...

**Comment by KronicDeth** [comment]
@jimmay5469 you need to handle the fact that the app itself is an app server running on port 4000 behind a ELB load balancer.  If ELB works like other load balancers, there should be a header that tell the app server, so phoenix, what the external DNS name is and that should be used.

**Comment by jimmay5469** [comment]
Ahh, thanks Luke!

**Comment by jimmay5469** [comment]
Unfortunately while this PR solves #414 it uncovers an additional bug when deploying the site behind ELB. I opened issue #435 to represent that.

**Pull request merged**
